name: release


# Only works on Master branch
on:
  workflow_dispatch:
  push:
    branches:
      - master

# Cancels an release workflows in progress
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: looker-open-source/reusable-actions/.github/workflows/marketplace-block-release.yml@main
    secrets: inherit
